create database customer_behavior;
use customer_behavior;
select * from customer;


-- Q1. What is the total Revenue generated by Male Vs. Female Customers?
select gender, sum(purchase_amount) as revenue 
from customer 
group by gender; 

-- Q2. Which customer used a discount but still spent more than average purchase amount?
select customer_id,purchase_amount 
from customer 
where discount_applied="Yes" 
and purchase_amount >= (select avg(purchase_amount) from customer);

-- Q3. Which are the top 5 products with the highest average rating?
SELECT 
    item_purchased,
    ROUND(AVG(review_rating), 1) AS Avg_review_rating
FROM
    customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

-- Q4.Compare the average Purchase Amount between Standard and Express Shipping.
SELECT 
    ROUND(AVG(purchase_amount), 2) AS Avg_purchase_amount,
    shipping_type
FROM
    customer
GROUP BY shipping_type
HAVING shipping_type = 'Express'
    OR shipping_type = 'Standard';

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and Non-subscribers.
SELECT 
    subscription_status,
    COUNT(customer_id) AS total_customers,
    ROUND(AVG(purchase_amount), 2) AS avg_spend,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM
    customer
GROUP BY subscription_status
ORDER BY total_revenue , avg_spend DESC;

-- Q6. Which 5 products have the highest percentage of purchase with discount applied?
SELECT 
    item_purchased,
    ROUND(100 * SUM(CASE
                WHEN discount_applied = 'Yes' THEN 1
                ELSE 0
            END) / COUNT(*),
            2) discount_rate
FROM
    customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Q7. Segment customer into new, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment. 
with customer_type as ( select customer_id,previous_purchases, case when previous_purchases =1 then "New"
when previous_purchases between 2 and 10 then "Returning"
else "Loyal" end as customer_segment
from customer)
select customer_segment, count(*) as "Number of Customers" from customer_type group by customer_segment;

-- Q8. What are the Top 3 most purchased product within each category?
with item_counts as (select category,
item_purchased,count(customer_id) as total_orders,
row_number() over (partition by category order by count(customer_id) desc) as item_rank
from customer group by category,item_purchased)

select item_rank, category,item_purchased,total_orders
from item_counts
where item_rank <=3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT 
    subscription_status, COUNT(customer_id) AS repeat_buyers
FROM
    customer
WHERE
    previous_purchases > 5
GROUP BY subscription_status;

-- Q10. What is the revenue contribution of each age group?
SELECT 
    age_group, SUM(purchase_amount) AS total_revenue
FROM
    customer
GROUP BY age_group
ORDER BY total_revenue DESC;


